### ISSUE TITLE
Specify node/resources for individual DVC pipeline stages running in Argo Workflows

### ISSUE THREAD

**Issue by paulsilcock** [paulsilcock/mlops#3]
Each DVC stage supports a `meta` section that could be used to provide details about which resources to use (e.g. selecting a GPU).

For example, given the following stage configuration, the Python script that dynamically generates our `Workflow` could easily parse the `meta.argo` section and inject this into the `podSpecPatch`:

```yaml
stages:
  myStage:
    cmd: ...
    meta:
      argo: 
        nodeSelector:
          nvidia.com/gpu: "true"
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        containerResources:
          limits:
            nvidia.com/gpu: 1
```

Alternatively, we could create some custom `WorkflowTemplates` for common use-cases. Currently, each individual task in the corresponding DAG uses [this](https://github.com/paulsilcock/app-of-apps/blob/main/argo-workflows/dvc-pipeline-wt.yaml) template to execute a stage. This would lead to less cumbersome `dvc.yaml` files, although the approach may not scale well.
